### ISSUE TITLE
Compute q(z| x, y) at test time

### ISSUE THREAD

**Issue by hoangcuong2011** [wang-h/Variational-NMT#1]
Hello,

I am reading your paper Variational Neural Machine Translation.

The paper is great! I was wondering one thing: How do you compute q(z| x, y) at test time? 
I cannot find an obvious approach to this as at test time we don't have y to compute their representation and then q(z| x, y).

Thanks!

Best,

**Comment by wang-h** [comment]
Hello,

First, those papers are not mine.

I computed q(z| x, y) as q(z| x, x) at the test time. I wonder whether the author of the VNMT paper handled it as same as what I did.

Thanks!

**Comment by hoangcuong2011** [comment]
Thx @wang-h. I asked the authors and they did as what you did indeed!

**Comment by PierreColombo** [comment]
During decoding, however, due to the absence of target
sentence y, we set hz to be the mean of pθ(z|x), i.e., µ prime.
it is reported in the paper
