### ISSUE TITLE
Kl loss wrong

### ISSUE THREAD

**Issue by PierreColombo** [wang-h/Variational-NMT#2]
z is a conditional distribution not sample from N(0,I)

**Comment by wang-h** [comment]
> z is a conditional distribution not sample from N(0,I)
see the following lines in VNMT.py:
            eps = Variable(std.data.new(std.size()).normal_())
            z = eps.mul(std).add_(mu)

z is generated by eps and eps is sampled from N(0,I) (see .normal_()).

**Comment by PierreColombo** [comment]
Check the paper.
